on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        working-directory: /backend-memories-code
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: /backend-memories-code
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_149025114A234FF4A40B13D28A174866 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F1777467EA84DA6ADC9CD17E8EC147F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_03D4F528C22B406894D1F1EE39BEE23F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'memories-backend'
          slot-name: 'Production'
          package: ./publish
